// import bcrypt from 'bcryptjs';

const data = {
  users: [
    // {
    //   name: 'Angga',
    //   email: 'jstcode.hub@gmail.com',
    //   password: bcrypt.hashSync('angga1508'),
    //   isAdmin: true,
    // },
  ],

  product: [
    {
      name: 'Pancake',
      slug: 'pancake-saudara',
      category: 'Food',
      image: '/images/pancake.png',
      price: '10000',
      brand: 'Pancake Saudara',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Jajanan favorit anak muda',
    },
    {
      name: 'Churros',
      slug: 'churros',
      category: 'Food',
      image: '/images/churros.png',
      price: '5000',
      brand: 'Churros',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Jajanan favorit anak muda',
    },
    {
      name: 'Masa SMK',
      slug: 'masa-smk',
      category: 'Drink',
      image: '/images/masa-smk.png',
      price: '5000',
      brand: 'Masa SMK',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Minuman favorit anak muda',
    },
    {
      name: 'Pisang Goreng',
      slug: 'pisang-uwu',
      category: 'Food',
      image: '/images/pisang-uwu.png',
      price: '5000',
      brand: 'Pisang Uwu',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Jajanan favorit anak muda',
    },
    {
      name: 'Sandwich',
      slug: 'skarisa-sandwich',
      category: 'Food',
      image: '/images/sandwich.png',
      price: '10000',
      brand: 'Skarisa Sandwich',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Jajanan favorit anak muda',
    },
    {
      name: 'Makaroni',
      slug: 'makaroni-kress',
      category: 'Food',
      image: '/images/makaroni.png',
      price: '5000',
      brand: 'Makaroni Kress',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Jajanan favorit anak muda',
    },
  ],
};

export default data;
